name: qrcode_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: ^4.6.6
  open_file_plus: ^3.4.1+1
  path_provider: ^2.1.4
  pdf: ^3.11.1
  qr_flutter: ^4.1.0

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
