// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeBHNbcASBIIVgHLMQyQHBHJx0SPBEqw',
    appId: '1:157915264096:web:e3cf1f58c9cbb6e9d9ff05',
    messagingSenderId: '157915264096',
    projectId: 'qrcode-42db9',
    authDomain: 'qrcode-42db9.firebaseapp.com',
    storageBucket: 'qrcode-42db9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqUcOopEve78meGjzAoeS51SKHNvuicO8',
    appId: '1:157915264096:android:2555a7e06d57df07d9ff05',
    messagingSenderId: '157915264096',
    projectId: 'qrcode-42db9',
    storageBucket: 'qrcode-42db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa4cCxUonkInFqbrgalUnwM4I0-Uv-osU',
    appId: '1:157915264096:ios:6d227c54efc57ac5d9ff05',
    messagingSenderId: '157915264096',
    projectId: 'qrcode-42db9',
    storageBucket: 'qrcode-42db9.appspot.com',
    iosBundleId: 'com.example.qrcodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa4cCxUonkInFqbrgalUnwM4I0-Uv-osU',
    appId: '1:157915264096:ios:6d227c54efc57ac5d9ff05',
    messagingSenderId: '157915264096',
    projectId: 'qrcode-42db9',
    storageBucket: 'qrcode-42db9.appspot.com',
    iosBundleId: 'com.example.qrcodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNeBHNbcASBIIVgHLMQyQHBHJx0SPBEqw',
    appId: '1:157915264096:web:d838c3ef4ac0bdaad9ff05',
    messagingSenderId: '157915264096',
    projectId: 'qrcode-42db9',
    authDomain: 'qrcode-42db9.firebaseapp.com',
    storageBucket: 'qrcode-42db9.appspot.com',
  );
}
